### ISSUE TITLE
some OpenCore settings do not work ...

### ISSUE THREAD

**Issue by roddy20** [n-d-k/NdkBootPicker#1]
Program itself works OK
but there is some kind of conflict with
AllowSetDefault=No, HideAuxiliary=Yes and Auxiliary=Yes
in OC config, it is impossible to show hidden Recovery HD by SPACE key etc

**Comment by n-d-k** [comment]
It's an initial version,  I am aware of the issue you mentioned, will fix them and make it behave just like text version.  Thanks for reporting!

**Comment by n-d-k** [comment]
Fixed as tested. v0.0.2
