### ISSUE TITLE
os_mac.icns instead os_moja.icns

### ISSUE THREAD

**Issue by lbuisson** [n-d-k/NdkBootPicker#11]
Hi,

On OC 0,57 with NDK I have os_mac.icns default icon instead os_moja.icns on bootscreen

But I have good icns and name inside 

![ScreenShot-2020-04-20-071035](https://user-images.githubusercontent.com/48549767/79733420-61f0f080-82f5-11ea-86d2-3d4031310467.png)

![image](https://user-images.githubusercontent.com/48549767/79733828-ff4c2480-82f5-11ea-8608-d71ba5fc71af.png)

**Comment by n-d-k** [comment]
You need to rename your MAC OS entry name to contain a Moja keyword, for example MAC MOJAVE OS.

**Comment by lbuisson** [comment]
It does work then I rename my os_moja.icns as os_mac.icns to work
![ScreenShot-2020-04-20-230324](https://user-images.githubusercontent.com/48549767/79808500-3fe78480-836e-11ea-9482-6b291e2e5060.png)

**Comment by Se7Touch** [comment]
Hello,

I'm added PrimeOS in OpenCore but can't see my OS icon..

Entry name: PrimeOS
Icon name: os_Prime or os_Pri etc.

*I tried other orginal icons.
