### ISSUE TITLE
is black screen without any display

### ISSUE THREAD

**Issue by Wilyte** [n-d-k/NdkBootPicker#12]
Hi n-d-k,

Thanks for your working awesome GUI, I'd like to have a try.

I've configed follow the Readme, and nothing show on screen after boot.

The OC is https://github.com/daliansky/XiaoXinPro-13-hackintosh/tree/v1.8/EFI/EFI-OC-PRO13-AOAC

v 1.8 OC 0.57

I've switch the drivers order follow https://github.com/n-d-k/NdkBootPicker/issues/3, still not working.

Pls tell how to debug and show the log to help solve the issue.

Thanks everyone!

**Comment by n-d-k** [comment]
v 1.8 is compiled against OC 0.57 binary instance, so it's necessary to use a matching pair to avoid incompatible issues.
