### ISSUE TITLE
shell output

### ISSUE THREAD

**Issue by roddy20** [n-d-k/NdkBootPicker#2]
version 0.2
EFI-shell output is printed over GUI as background, not blank screen

**Comment by roddy20** [comment]
... and the background is black, not "Background.png"

**Comment by n-d-k** [comment]
Currently, there isn't any function to resize the Background.png to match with the screen resolution, so it need to be resized by user to match the screen resolution for it to load.  If the size doesn't match it won't load.   Background.png auto resizing will be implemented  sometimes later.

**Comment by n-d-k** [comment]
Resolved in v0.0.3
