### ISSUE TITLE
This UEFI driver hangs the OC boot process

### ISSUE THREAD

**Issue by MacNB** [n-d-k/NdkBootPicker#3]
Nice Boot Device Selector. The problem is the placement order in the UEFI drivers section of the OC config.plist file. It hangs if placed at the end of all the drivers:

`<key>UEFI</key>
	<dict>
		<key>ConnectDrivers</key>
		<true/>
		<key>Drivers</key>
		<array>
			<string>HFSPlus.efi</string>
			<string>ApfsDriverLoader.efi</string>
			<string>FwRuntimeServices.efi</string>
			<string>FireWireOhci.efi</string>
			<string>AudioDxe.efi</string>
			<string>BootChimeDxe.efi</string>
			<string>NdkBootPicker.efi</string>
		</array>`

Workaround:
Move the NdkBootPicker to the top of the list of drivers:

`<key>UEFI</key>
	<dict>
		<key>ConnectDrivers</key>
		<true/>
		<key>Drivers</key>
		<array>
			<string>NdkBootPicker.efi</string>
			<string>HFSPlus.efi</string>
			<string>ApfsDriverLoader.efi</string>
			<string>FwRuntimeServices.efi</string>
			<string>FireWireOhci.efi</string>
			<string>AudioDxe.efi</string>
			<string>BootChimeDxe.efi</string>
		</array>`
		
Not sure where the problem is but suggest the workaround is documented in the README.MD
Thanks for your work.

BTW, I mentioned the problem when you announced the new picker here:
https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?page=129&tab=comments#comment-2708779

**Comment by n-d-k** [comment]
Thanks MacNB,

FireWireOhci.efi, AudioDxe.efi, BootChimeDxe.efi, one of these driver may cause the conflict with NdkBootPicker if loaded first. Thanks for the figure out the work around.

**Comment by MacNB** [comment]
I tested various combination of positioning your driver in the config.plist.
The issue is with the BootChimeDxe.efi.
As a test, I put that driver at the top and when OC tries to load the next driver (after BootChimeDxe.efi), it hangs.

So it looks like BootChimeDxe.efi is leaving the loaded state with a "bomb".
I don't know the enough about UEFI and the protocol for loading each .efi to be able debug further.
I guess the issue should be reported tot he BootChimeDxe.efi author.

The workaround is: **load BootChimeDxe.efi LAST**.

Here are the last few lines from the log:

_01:256 00:065 OC: Got 8 drivers
01:288 00:032 OC: Driver BootChimeDxe.efi at 0 is being loaded...
01:448 00:159 OC: Driver BootChimeDxe.efi at 0 is successfully loaded!
01:483 00:034 OC: Driver HFSPlus.efi at 1 is being loaded..._

This issue can be closed.
Thanks

**Comment by roddy20** [comment]
BootChime.efi plays audiofile for 2 seconds approx, maybe it is the reason of error when loading the next driver?

**Comment by MacNB** [comment]
@roddy20 I think not. The bootchime.efi does not trigger playback after it is loaded but just before booting the selected OS.

When using a boot picker in OC (either the builtin or NDK's), there's no sound playback when the picker menus appear. It only plays the chime when the user hits Enter after selecting the OS to boot.

**Comment by roddy20** [comment]
yes, you are right
I ll try it with different order a little later and I ll let you know if there will be anything interesting

**Comment by n-d-k** [comment]
Thank you very much MacNB for troubleshooting further on this.  I'll put a note on README to warn user about the BootChimeDxe.efi.

**Comment by MacNB** [comment]
@n-d-k Thanks for updating the readme.md. May I make a suggestion that you amend the *Note to make more clear as to what people should do to work around the issue. How about the following text:
*Note: For users who is using BootChimeDxe.efi, this driver seems to prevent any other drivers to load and cause system hang after BootChimeDxe.efi was loaded. To prevent a system hang, make sure that NdkBootPicker.efi (and all other EFI drivers) are loaded BEFORE BootChimeDxe.efi. This can be achieved by making sure that BootChimeDxe.efi is the last driver in the UEFI->Drivers section of the OpenCore config.plist file.

**Comment by Wilyte** [comment]
Update:

There is not work for me, open a new issue for discussion.

Original:

I've configed follow the Readme, and nothing show on screen after boot.

I will try again after read this issue, then feedback the result.

The OC drivers list https://github.com/daliansky/XiaoXinPro-13-hackintosh/tree/master/EFI/EFI-OC-PRO13-AOAC/OC/Drivers

Thanks everyone!
