### ISSUE TITLE
issue with iMac A1312 27''

### ISSUE THREAD

**Issue by bayard1965** [n-d-k/NdkBootPicker#4]
My opencore config works well, but when i try to use your Graphic Picker loading NdkBootPicker.efi the boot process stop before loading the graphical interface. the last line in log file is OCUI: Initialize HiiFont...Success and nothing happen after.
[opencore-2020-02-22-211749.txt](https://github.com/n-d-k/NdkBootPicker/files/4239999/opencore-2020-02-22-211749.txt)
[config.plist.zip](https://github.com/n-d-k/NdkBootPicker/files/4240003/config.plist.zip)

**Comment by n-d-k** [comment]
Did you copy the Icons folder to EFI\OC?

**Comment by bayard1965** [comment]
Yes I have copied the icons folder to /EFI/OC. Your first graphic interface without icons was working well using your fork.
But I cannot boot with the new versions using icons with the your fork or loading your efi driver in official open core.
And trying to load HiiDatabase.efi in official open core without loading NdkBootPicker.efi result in boot process stopping trying to load HiiDatabase.efi. So it’s seems related to HiiDatabase.efi.

**Comment by n-d-k** [comment]
Hii stuff may not be compatible with older bios version. I am about to switch to not using HiiFont protocol, so hang on....if HiiFont does not work with your system.

**Comment by bayard1965** [comment]
Ok, I’ll let you know how it works if you this way. Thanks.

**Comment by n-d-k** [comment]
You can try the new commit, it no longer use HiiFont protocol anymore.
