### ISSUE TITLE
Is the filename for background4k.png correct?

### ISSUE THREAD

**Issue by sspilleman** [n-d-k/NdkBootPicker#5]
Hi!

Thanks for developing this! Really appreciate it. I haven't tried it yet, I wanted to analyse first. I have one question / remark. Looking at the source:

```C
  if (FileExist (L"EFI\\OC\\Icons\\Background4k.png") && mScreenHeight >= 2160) {
    mBackgroundImage = DecodePNGFile (L"EFI\\OC\\Icons\\Background4k.png");
  } else if (FileExist (L"EFI\\OC\\Icons\\Background.png")) {
    mBackgroundImage = DecodePNGFile (L"EFI\\OC\\Icons\\Background.png");
  }
```

I see you're trying to locate L"EFI\\OC\\Icons\\Background4k.png". Looking at the Icons folder I see it is there, but named differently as "background4k.png" (without capital "B"). Is that correct, or isn't it cases sensitive anyway?

Tx,
Sander

**Comment by n-d-k** [comment]
It's not case sensitive!
