### ISSUE TITLE
Black Screen on boot, internal GPU on 4K monitor

### ISSUE THREAD

**Issue by sspilleman** [n-d-k/NdkBootPicker#7]
Hi NDK,

I performed the following steps:

1. I cloned the
1. I buillt NdkBootPicker.efi by runnning "./ndk-macbuild.tool" 
1. I copied NdkBootPicker.efi to OC/Drivers
1. I copied Icons to OC/Icons
1. I changed PickerMode to External in config.plist

If I reboot, I get a black screen......
I'm running on OpenCore v0.5.6 on 9900K Built-in GPU with a 4K monitor. 

Do you have any suggestions on what to do / what to change? I also see some post on "BootLiquor". Is that the same thing with a different name?

Thanks.

Sander

**Comment by h9826790** [comment]
> Hi NDK,
> 
> I performed the following steps:
> 
> 1. I cloned the
> 2. I buillt NdkBootPicker.efi by runnning "./ndk-macbuild.tool"
> 3. I copied NdkBootPicker.efi to OC/Drivers
> 4. I copied Icons to OC/Icons
> 5. I changed PickerMode to External in config.plist
> 
> If I reboot, I get a black screen......
> I'm running on OpenCore v0.5.6 on 9900K Built-in GPU with a 4K monitor.
> 
> Do you have any suggestions on what to do / what to change? I also see some post on "BootLiquor". Is that the same thing with a different name?
> 
> Thanks.
> 
> Sander

Did you add `<string>NdkBootPicker.efi</string>` under `Drivers` (inside config.plist)?

**Comment by n-d-k** [comment]
Hi guys, 
Whenever you compile a new NdkBootPicker.efi, it's compiled against the latest/current OC source code. So it's necessary that you need to compile the latest/current OC source code to run it. If you're running the OC binary release, then there's NdkBootPicker.efi binary release that support the OC binary version.

**Comment by sspilleman** [comment]
Thanks. I nu downloaded the latest release (0.1.7) that works with OC 0.5.6... It works!.... kinda. The resolution seems "way" too low on my 4K screen. Could it be that the display is set to 1920x1080 instead of 3640x2160 somehow? I did resize the background.png to 4K, but its not just the bg that looks crappy

**Comment by n-d-k** [comment]
Default theme was for 1080p screen, since majority still using it.  Scaling up to 4k will make thing look like what you described.  I will soon release 4k theme with all high resolution icons and images which should look much better on 4k screen.

**Comment by sspilleman** [comment]
Thanks NDK!!!!
