### ISSUE TITLE
with OpenCanopy.efi used. cant use this picker

### ISSUE THREAD

**Issue by west-shell** [n-d-k/NdkBootPicker#8]
I am using OpenCanopy .When I deleted OpenCanopy.efi in drivers of config.plist and add this picker .it cant boot. What should I do to use this picker

**Comment by n-d-k** [comment]
Make sure you are using the right version of NdkBootPicker.efi, and Icons folder is in EFI\OC folder. If you compile the latest source, then you need to compile and use the latest OC source as well.  If you use OC binary release version, then down load the NdkBootPicker binary release which state the OC version it supported.
