### ISSUE TITLE
Too hightlight on selection

### ISSUE THREAD

**Issue by lbuisson** [n-d-k/NdkBootPicker#9]
Hi

I made test with my create theme and I have issue with highlight selection, it is too more lightning.
Have you a solution or setting to keep same color as original?

Thank you

![ScreenShot-2020-04-20-071035](https://user-images.githubusercontent.com/48549767/79732685-505b1900-82f4-11ea-8424-95816b3c9bf3.png)

**Comment by n-d-k** [comment]
This is a designed choice, there's no easy option to set it.  But there's a way to adjust it if you compile the NdkBootPicker.efi from the source, all you have to do is adjust the number in NdkBootPicker.h to your liking, the default is 80, you can set to 0 if you like your selected icon not change its color. 
https://github.com/n-d-k/NdkBootPicker/blob/master/NdkBootPicker.h#L161
